### ISSUE TITLE
A

### ISSUE THREAD

**Issue by rahimi7k** [M3ikShizuka/instagram-private-api#1]

**Comment by M3ikShizuka** [comment]
Hello @[rahimi7k](https://github.com/rahimi7k).
The algorithm you need is in the file signinEncryptData.js is JavaScript code (not NodeJs). 

Uncomment the generatePostDataForSignIn() call and fill your data into its arguments. After that, open index.html in your browser and get the generated data string. Use any REST API tool to send a request with the generated data to the instagram server. And don't forget the CSRF-token.

If you got success everything is working correctly.

Line: https://github.com/M3ikShizuka/instagram-private-api/blob/28bf18e4ca1b6c43a7c6ef6fd850fa9023f4d22f/signinEncryptData.js#L270

**Comment by M3ikShizuka** [comment]
@[rahimi7k](https://github.com/rahimi7k)
I did not reverse the #PWD_INSTAGRAM that is used in the applications. I didn't have the technical ability to do that at the time. At the moment there is only #PWD_INSTAGRAM_BROWSER in this repository.

I'm not sure I can find free time to research #PWD_INSTAGRAM anytime soon.

**Comment by rahimi7k** [comment]
OK, Thank you for the reply
